# Generated by Django 4.0.4 on 2022-04-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_comment_options_remove_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
